version: '3.8'
services:
  # --- PART-I: Manual Deployment (Must be UP) ---
  db-part1:
    image: mysql:5.7
    container_name: mysql_db_part1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data_part1:/var/lib/mysql

  api-part1:
    image: aalijahx/bezkoder-api:latest
    container_name: api_part1
    ports:
      - "8080:8080"
    depends_on:
      - db-part1

  ui-part1:
    image: aalijahx/bezkoder-ui:latest
    container_name: ui_part1
    ports:
      - "6868:80"

  # --- PART-II: Automation (Must be DOWN initially) ---
  api-automation:
    image: aalijahx/bezkoder-api:latest
    container_name: api_part2
    ports:
      - "8082:8080"

  ui-automation:
    image: aalijahx/bezkoder-ui:latest
    container_name: ui_part2
    ports:
      - "9000:80"

volumes:
  db_data_part1:
